name: Android Full Builder (32 & 64 bit)

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.25.2
  LLVM_VERSION: 15.0.6
  NDK_VERSION: r25b

jobs:
  delete_latest_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: delete latest release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_android_all:
    runs-on: ubuntu-latest
    needs: delete_latest_release
    permissions:
      contents: write
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: init linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile arm64-v8a (64-bit)
      run: |
        python3 scripts/platform_builder.py --platform=android --arch=arm64-v8a --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android/
        # Kompres hasil 64-bit
        cd build
        tar -zcvf dobby-android-arm64.tar.gz android/
        cp dobby-android-arm64.tar.gz ../artifact/
        cd ..
      shell: bash

    - name: compile armeabi-v7a (32-bit)
      run: |
        # Hapus folder build lama agar tidak tercampur
        rm -rf build/android/arm64-v8a
        python3 scripts/platform_builder.py --platform=android --arch=armeabi-v7a --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        # Kompres hasil 32-bit
        cd build
        tar -zcvf dobby-android-arm32.tar.gz android/
        cp dobby-android-arm32.tar.gz ../artifact/
        cd ..
      shell: bash

    - name: update release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        body: "Dobby build otomatis untuk Android 64-bit (arm64-v8a) dan 32-bit (armeabi-v7a)"
        # Mengunggah semua file .tar.gz yang ada di folder artifact
        artifacts: "artifact/*.tar.gz" 
        allowUpdates: true
        replacesArtifacts: true
